// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: scprotobuf/item.proto

package scprotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Guid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lo *uint64 `protobuf:"fixed64,1,opt,name=lo,proto3,oneof" json:"lo,omitempty"`
	Hi *uint64 `protobuf:"fixed64,2,opt,name=hi,proto3,oneof" json:"hi,omitempty"`
}

func (x *Guid) Reset() {
	*x = Guid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guid) ProtoMessage() {}

func (x *Guid) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guid.ProtoReflect.Descriptor instead.
func (*Guid) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{0}
}

func (x *Guid) GetLo() uint64 {
	if x != nil && x.Lo != nil {
		return *x.Lo
	}
	return 0
}

func (x *Guid) GetHi() uint64 {
	if x != nil && x.Hi != nil {
		return *x.Hi
	}
	return 0
}

type ItemsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemDefinitions []*MappedItemRecord         `protobuf:"bytes,1,rep,name=ItemDefinitions,proto3" json:"ItemDefinitions,omitempty"`
	SharedData      []*MappedSharedData         `protobuf:"bytes,2,rep,name=SharedData,proto3" json:"SharedData,omitempty"`
	LanguageData    []*MappedItemsLanguagesData `protobuf:"bytes,3,rep,name=LanguageData,proto3" json:"LanguageData,omitempty"`
}

func (x *ItemsData) Reset() {
	*x = ItemsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsData) ProtoMessage() {}

func (x *ItemsData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsData.ProtoReflect.Descriptor instead.
func (*ItemsData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemsData) GetItemDefinitions() []*MappedItemRecord {
	if x != nil {
		return x.ItemDefinitions
	}
	return nil
}

func (x *ItemsData) GetSharedData() []*MappedSharedData {
	if x != nil {
		return x.SharedData
	}
	return nil
}

func (x *ItemsData) GetLanguageData() []*MappedItemsLanguagesData {
	if x != nil {
		return x.LanguageData
	}
	return nil
}

type MappedItemRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   *Guid       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Item *ItemRecord `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
}

func (x *MappedItemRecord) Reset() {
	*x = MappedItemRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedItemRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedItemRecord) ProtoMessage() {}

func (x *MappedItemRecord) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedItemRecord.ProtoReflect.Descriptor instead.
func (*MappedItemRecord) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{2}
}

func (x *MappedItemRecord) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MappedItemRecord) GetItem() *ItemRecord {
	if x != nil {
		return x.Item
	}
	return nil
}

type ItemRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         *Guid  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID   *Guid  `protobuf:"bytes,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	TemplateID *Guid  `protobuf:"bytes,4,opt,name=TemplateID,proto3" json:"TemplateID,omitempty"`
	MasterID   *Guid  `protobuf:"bytes,5,opt,name=MasterID,proto3" json:"MasterID,omitempty"`
}

func (x *ItemRecord) Reset() {
	*x = ItemRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRecord) ProtoMessage() {}

func (x *ItemRecord) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRecord.ProtoReflect.Descriptor instead.
func (*ItemRecord) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemRecord) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *ItemRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRecord) GetParentID() *Guid {
	if x != nil {
		return x.ParentID
	}
	return nil
}

func (x *ItemRecord) GetTemplateID() *Guid {
	if x != nil {
		return x.TemplateID
	}
	return nil
}

func (x *ItemRecord) GetMasterID() *Guid {
	if x != nil {
		return x.MasterID
	}
	return nil
}

type MappedSharedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              *Guid                   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SharedDataItems []*MappedSharedDataItem `protobuf:"bytes,2,rep,name=SharedDataItems,proto3" json:"SharedDataItems,omitempty"`
}

func (x *MappedSharedData) Reset() {
	*x = MappedSharedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedSharedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSharedData) ProtoMessage() {}

func (x *MappedSharedData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSharedData.ProtoReflect.Descriptor instead.
func (*MappedSharedData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{4}
}

func (x *MappedSharedData) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MappedSharedData) GetSharedDataItems() []*MappedSharedDataItem {
	if x != nil {
		return x.SharedDataItems
	}
	return nil
}

type MappedSharedDataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    *Guid  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MappedSharedDataItem) Reset() {
	*x = MappedSharedDataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedSharedDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSharedDataItem) ProtoMessage() {}

func (x *MappedSharedDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSharedDataItem.ProtoReflect.Descriptor instead.
func (*MappedSharedDataItem) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{5}
}

func (x *MappedSharedDataItem) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MappedSharedDataItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MappedItemsLanguagesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           *Guid                      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LanguageData []*MappedItemLanguagesData `protobuf:"bytes,2,rep,name=LanguageData,proto3" json:"LanguageData,omitempty"`
}

func (x *MappedItemsLanguagesData) Reset() {
	*x = MappedItemsLanguagesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedItemsLanguagesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedItemsLanguagesData) ProtoMessage() {}

func (x *MappedItemsLanguagesData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedItemsLanguagesData.ProtoReflect.Descriptor instead.
func (*MappedItemsLanguagesData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{6}
}

func (x *MappedItemsLanguagesData) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MappedItemsLanguagesData) GetLanguageData() []*MappedItemLanguagesData {
	if x != nil {
		return x.LanguageData
	}
	return nil
}

type MappedItemLanguagesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language     string                `protobuf:"bytes,1,opt,name=Language,proto3" json:"Language,omitempty"`
	VersionsData []*MappedVersionsData `protobuf:"bytes,2,rep,name=VersionsData,proto3" json:"VersionsData,omitempty"`
}

func (x *MappedItemLanguagesData) Reset() {
	*x = MappedItemLanguagesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedItemLanguagesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedItemLanguagesData) ProtoMessage() {}

func (x *MappedItemLanguagesData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedItemLanguagesData.ProtoReflect.Descriptor instead.
func (*MappedItemLanguagesData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{7}
}

func (x *MappedItemLanguagesData) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MappedItemLanguagesData) GetVersionsData() []*MappedVersionsData {
	if x != nil {
		return x.VersionsData
	}
	return nil
}

type MappedVersionsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32               `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Fields  []*MappedFieldsData `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
}

func (x *MappedVersionsData) Reset() {
	*x = MappedVersionsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedVersionsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedVersionsData) ProtoMessage() {}

func (x *MappedVersionsData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedVersionsData.ProtoReflect.Descriptor instead.
func (*MappedVersionsData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{8}
}

func (x *MappedVersionsData) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MappedVersionsData) GetFields() []*MappedFieldsData {
	if x != nil {
		return x.Fields
	}
	return nil
}

type MappedFieldsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    *Guid  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MappedFieldsData) Reset() {
	*x = MappedFieldsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scprotobuf_item_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedFieldsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedFieldsData) ProtoMessage() {}

func (x *MappedFieldsData) ProtoReflect() protoreflect.Message {
	mi := &file_scprotobuf_item_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedFieldsData.ProtoReflect.Descriptor instead.
func (*MappedFieldsData) Descriptor() ([]byte, []int) {
	return file_scprotobuf_item_proto_rawDescGZIP(), []int{9}
}

func (x *MappedFieldsData) GetID() *Guid {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MappedFieldsData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_scprotobuf_item_proto protoreflect.FileDescriptor

var file_scprotobuf_item_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x74, 0x65,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x04, 0x47, 0x75, 0x69, 0x64, 0x12,
	0x13, 0x0a, 0x02, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x02, 0x6c,
	0x6f, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06,
	0x48, 0x01, 0x52, 0x02, 0x68, 0x69, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6c, 0x6f,
	0x42, 0x05, 0x0a, 0x03, 0x5f, 0x68, 0x69, 0x22, 0xba, 0x01, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0f, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x0f, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x15, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x1f, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x15, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75,
	0x69, 0x64, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x50, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47,
	0x75, 0x69, 0x64, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x25, 0x0a,
	0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x44, 0x12, 0x21, 0x0a, 0x08, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x08, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6a, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x70, 0x65,
	0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x3f, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x43, 0x0a, 0x14, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6f, 0x0a, 0x18, 0x4d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x02, 0x49, 0x44, 0x12, 0x3c, 0x0a, 0x0c, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x17, 0x4d, 0x61, 0x70,
	0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x37, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x12, 0x4d, 0x61, 0x70,
	0x70, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x22, 0x3f, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e, 0x2f, 0x73, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scprotobuf_item_proto_rawDescOnce sync.Once
	file_scprotobuf_item_proto_rawDescData = file_scprotobuf_item_proto_rawDesc
)

func file_scprotobuf_item_proto_rawDescGZIP() []byte {
	file_scprotobuf_item_proto_rawDescOnce.Do(func() {
		file_scprotobuf_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_scprotobuf_item_proto_rawDescData)
	})
	return file_scprotobuf_item_proto_rawDescData
}

var file_scprotobuf_item_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_scprotobuf_item_proto_goTypes = []interface{}{
	(*Guid)(nil),                     // 0: Guid
	(*ItemsData)(nil),                // 1: ItemsData
	(*MappedItemRecord)(nil),         // 2: MappedItemRecord
	(*ItemRecord)(nil),               // 3: ItemRecord
	(*MappedSharedData)(nil),         // 4: MappedSharedData
	(*MappedSharedDataItem)(nil),     // 5: MappedSharedDataItem
	(*MappedItemsLanguagesData)(nil), // 6: MappedItemsLanguagesData
	(*MappedItemLanguagesData)(nil),  // 7: MappedItemLanguagesData
	(*MappedVersionsData)(nil),       // 8: MappedVersionsData
	(*MappedFieldsData)(nil),         // 9: MappedFieldsData
}
var file_scprotobuf_item_proto_depIdxs = []int32{
	2,  // 0: ItemsData.ItemDefinitions:type_name -> MappedItemRecord
	4,  // 1: ItemsData.SharedData:type_name -> MappedSharedData
	6,  // 2: ItemsData.LanguageData:type_name -> MappedItemsLanguagesData
	0,  // 3: MappedItemRecord.ID:type_name -> Guid
	3,  // 4: MappedItemRecord.Item:type_name -> ItemRecord
	0,  // 5: ItemRecord.ID:type_name -> Guid
	0,  // 6: ItemRecord.ParentID:type_name -> Guid
	0,  // 7: ItemRecord.TemplateID:type_name -> Guid
	0,  // 8: ItemRecord.MasterID:type_name -> Guid
	0,  // 9: MappedSharedData.ID:type_name -> Guid
	5,  // 10: MappedSharedData.SharedDataItems:type_name -> MappedSharedDataItem
	0,  // 11: MappedSharedDataItem.ID:type_name -> Guid
	0,  // 12: MappedItemsLanguagesData.ID:type_name -> Guid
	7,  // 13: MappedItemsLanguagesData.LanguageData:type_name -> MappedItemLanguagesData
	8,  // 14: MappedItemLanguagesData.VersionsData:type_name -> MappedVersionsData
	9,  // 15: MappedVersionsData.Fields:type_name -> MappedFieldsData
	0,  // 16: MappedFieldsData.ID:type_name -> Guid
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_scprotobuf_item_proto_init() }
func file_scprotobuf_item_proto_init() {
	if File_scprotobuf_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scprotobuf_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedItemRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedSharedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedSharedDataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedItemsLanguagesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedItemLanguagesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedVersionsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scprotobuf_item_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedFieldsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scprotobuf_item_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scprotobuf_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scprotobuf_item_proto_goTypes,
		DependencyIndexes: file_scprotobuf_item_proto_depIdxs,
		MessageInfos:      file_scprotobuf_item_proto_msgTypes,
	}.Build()
	File_scprotobuf_item_proto = out.File
	file_scprotobuf_item_proto_rawDesc = nil
	file_scprotobuf_item_proto_goTypes = nil
	file_scprotobuf_item_proto_depIdxs = nil
}
